package no.uia.todo.view.list

import androidx.lifecycle.ViewModelProvider
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.lifecycle.Observer
import androidx.navigation.fragment.findNavController
import androidx.recyclerview.widget.DefaultItemAnimator
import androidx.recyclerview.widget.LinearLayoutManager
import kotlinx.android.synthetic.main.todo_list_fragment.view.*
import no.uia.todo.R
import no.uia.todo.databinding.TodoListFragmentBinding
import no.uia.todo.viewmodel.ToDoViewModel

class ToDoListFragment : Fragment() {
    private val LOG_TAG: String = "ToDo:ToDoListFragment"

    private var _binding: TodoListFragmentBinding? = null
    private val binding get() = _binding!!

    private lateinit var viewModel: ToDoViewModel

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = TodoListFragmentBinding.inflate(layoutInflater, container, false)
        val view = binding.root

        viewModel = ViewModelProvider(this).get(ToDoViewModel::class.java)

        val onClickToDo = { pos:Int ->
            // Classes generated by nav_graph.xml
            val arg = ToDoListFragmentDirections.actionToDoListFragmentToToDoItemFragment(pos)
            findNavController().navigate(arg)
        }

        val adapter = ToDoListAdapter(viewModel.getToDos(), onClickToDo)
        view.ToDo_List_Recycler.adapter = adapter
        view.ToDo_List_Recycler.layoutManager = LinearLayoutManager(requireActivity())
        view.ToDo_List_Recycler.itemAnimator = DefaultItemAnimator()

        view.add_ToDo_fab.setOnClickListener {
            findNavController().navigate(R.id.toDoListAddDialog)
        }

        return view
    }
}