package no.uia.todo

import androidx.lifecycle.ViewModelProvider
import android.os.Bundle
import android.util.Log
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.fragment.findNavController
import androidx.recyclerview.widget.LinearLayoutManager
import kotlinx.android.synthetic.main.todo_list_fragment.view.*
import no.uia.todo.data.ToDo
import no.uia.todo.databinding.TodoListFragmentBinding
import no.uia.todo.viewmodel.ToDoViewModel

class ToDoListFragment : Fragment() {
    private val LOG_TAG: String = "ToDo:ToDoListFragment"

    private var _binding: TodoListFragmentBinding? = null
    private val binding get() = _binding!!

    private lateinit var viewModel: ToDoViewModel

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = TodoListFragmentBinding.inflate(layoutInflater, container, false)
        val view = binding.root

        viewModel = ViewModelProvider(this).get(ToDoViewModel::class.java)
        val onClickToDo = { pos:Int ->
            // Classes generated by nav_graph.xml
            val arg = ToDoListFragmentDirections.actionToDoListFragmentToToDoItemFragment(pos)
            findNavController().navigate(arg)
        }


        view.addToDo.setOnClickListener {
            val newToDo = ToDo(view.add_new_ToDo_editText.text.toString(), mutableListOf())
            viewModel.insertToDo(newToDo)
        }

        view.todoRecycler.layoutManager = LinearLayoutManager(requireActivity())
        view.todoRecycler.adapter = ToDoAdapter(viewModel.getToDos(), onClickToDo)

        return view
    }
}